DROP TABLE IF EXISTS `#__nycc_locations`;
CREATE TABLE `#__nycc_locations` (
	`id`     INT(11)     NOT NULL AUTO_INCREMENT,
	`name`   VARCHAR(50) NOT NULL,
  `addr1`  VARCHAR(100) NOT NULL DEFAULT '',
  `addr2`  VARCHAR(100) NOT NULL DEFAULT '',
  `city`   VARCHAR(50) NOT NULL DEFAULT '',
  `state`  VARCHAR(2) NOT NULL DEFAULT 'NY',
  `zip`    VARCHAR(10) NOT NULL DEFAULT '',
	`active` TINYINT(4) NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	AUTO_INCREMENT =0
	DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `#__nycc_rates`;
CREATE TABLE `#__nycc_rates` (
	`id`     INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`label`  VARCHAR(25) NOT NULL,
	`price`  FLOAT(7,2) NOT NULL DEFAULT '0.00',
	`active` TINYINT(4) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	DEFAULT CHARSET =utf8;
