DROP TABLE IF EXISTS `#__nycc_locations`;
CREATE TABLE `#__nycc_locations` (
	`id`     BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name`   VARCHAR(50) NOT NULL,
  `addr1`  VARCHAR(100) NOT NULL DEFAULT '',
  `addr2`  VARCHAR(100) NOT NULL DEFAULT '',
  `city`   VARCHAR(50) NOT NULL DEFAULT '',
  `state`  VARCHAR(2) NOT NULL DEFAULT 'NY',
  `zip`    VARCHAR(10) NOT NULL DEFAULT '',
	`active` TINYINT(4) NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `#__nycc_rates`;
CREATE TABLE `#__nycc_rates` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`label` VARCHAR(25) NOT NULL,
	`modifier` FLOAT(7,2) NOT NULL DEFAULT '0.00',
	`is_multiplier` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`active` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
	ENGINE=MyISAM
	DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `#__nycc_events`;
CREATE TABLE `#__nycc_events` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`main_location` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`short_description` VARCHAR(250) NOT NULL,
	`long_description` TEXT NOT NULL,
	`schedule` TEXT NOT NULL,
	`active` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	DEFAULT CHARSET =utf8;

CREATE TABLE `#__nycc_venues` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`event_id` BIGINT(20) UNSIGNED NOT NULL,
	`display_name` VARCHAR(50) NOT NULL DEFAULT '',
	`location_id` BIGINT(20) UNSIGNED NOT NULL,
	`event_date` BIGINT(20) UNSIGNED NOT NULL,
	`active` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	DEFAULT CHARSET =utf8;

DROP TABLE IF EXISTS `#__nycc_venue_rates`;
CREATE TABLE `#__venue_rates` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`venue_id` BIGINT(20) UNSIGNED NOT NULL,
	`rate_id` BIGINT(20) UNSIGNED NOT NULL,
	`active` BIGINT(20) UNSIGNED NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`)
)
	ENGINE=MyISAM;
